apiVersion: v1
kind: Service
metadata:
  name: spring-service-reaction
  namespace: devops
spec:
  selector:
    app: reaction-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 32084
  type: NodePort